services:
  redis:
    image: redis:alpine
    ports:
      - 2000:6379
    networks:
      - app_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - backend

networks:
  app_network:
    driver: bridge